name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017

    steps:
    - uses: actions/checkout@v2

    # Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    # Install Backend Dependencies
    - name: Install Backend Dependencies
      working-directory: ./backend
      run: npm install

    # Run Backend Tests
    - name: Run Backend Tests
      working-directory: ./backend
      run: npm test

    # Install Frontend Dependencies
    - name: Install Frontend Dependencies
      working-directory: ./frontend
      run: npm install

    # Run Frontend Tests
    - name: Run Frontend Tests
      working-directory: ./frontend
      run: npm test

    # Build and Push Docker Images
    - name: Build and Push Docker Images
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        # Build backend and frontend Docker images
        docker build -t yourdockerhubusername/backend ./backend
        docker build -t yourdockerhubusername/frontend ./frontend

        # Push to Docker Hub
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push yourdockerhubusername/backend
        docker push yourdockerhubusername/frontend

    # Deploy to AWS Elastic Beanstalk
    - name: Deploy to AWS Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        application_name: your-eb-application-name
        environment_name: your-eb-environment-name
        version_label: ${{ github.sha }}
        region: your-aws-region
        bucket_name: your-s3-bucket-for-eb
        bucket_key: your-app/${{ github.sha }}.zip
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
